### ISSUE TITLE
Implement String.prototype.padEnd

### ISSUE THREAD

**Issue by msn0** [msn0/mdn-polyfills#18]
Implement a polyfill for String.prototype.padEnd as per https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padEnd#Polyfill

**Comment by smehta11** [comment]
I'll try this out!

**Comment by smehta11** [comment]
Just kidding hah

**Comment by rixlabs** [comment]
Sorry it was very similar to the other so it took me just minutes
