### ISSUE TITLE
Implement Object.is polyfill

### ISSUE THREAD

**Issue by msn0** [msn0/mdn-polyfills#30]
Implement `Object.is` polyfill as per https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is

**Comment by pthomas931** [comment]
I'm assuming you are looking for a polyfill for IE?
It looks like most browsers have it implemented from here: 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is#Browser_compatibility

**Comment by msn0** [comment]
According to mdn IE is missing this feature. This issue is about to copy the polyfill and have it in here.
