### ISSUE TITLE
Add Number.isNaN polyfill

### ISSUE THREAD

**Issue by missmatsuko** [msn0/mdn-polyfills#39]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN

**Comment by msn0** [comment]
Just added this polyfill. Number.isNaN is published within 5.10.0

https://github.com/msn0/mdn-polyfills/releases/tag/5.10.0

**Comment by missmatsuko** [comment]
@msn0 Thank you! That was quick! :)
