### ISSUE TITLE
In order to support IE, polyfills should be contained in one file, and not ES6 modules (import/export.)

### ISSUE THREAD

**Issue by blzaugg** [msn0/mdn-polyfills#54]
I'm attempting to use `String.prototype.endsWith` and noticed that it uses import/export. This ends up failing in IE11, which defeats the purpose of polyfilling IE.

**Comment by msn0** [comment]
npm package contains bundled version of `String.prototype.endsWith`.

You should use it this way:

```js
import 'mdn-polyfills/String.prototype.endsWith';
```

or

```js
require('mdn-polyfills/String.prototype.endsWith');
```

or use a cdn, for example

```html
<script src="https://unpkg.com/mdn-polyfills@5.15.1/String.prototype.endsWith"></script>
```
