### ISSUE TITLE
Element.prototype.classList error

### ISSUE THREAD

**Issue by niksy** [msn0/mdn-polyfills#56]
`Element.prototype.closest` returns following error when used:

```js
'ele' is undefined
```

**Comment by msn0** [comment]
Please write some more details - which browser and which version of mdn-polyfills?

**Comment by niksy** [comment]
IE9, latest version of `mdn-polyfills`.

**Comment by msn0** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Element/classList$compare?from=1529567&to=1542773&utm_campaign=Wiki+Doc+Edits&utm_medium=email&utm_source=developer.mozilla.org

**Comment by missmatsuko** [comment]
Just got the same problem here.

**Comment by msn0** [comment]
Good to hear! I'll publish latest version from mdn. Stay tuned 😎

**Comment by msn0** [comment]
📦 mdn-polyfills@5.16.1
