### ISSUE TITLE
Add Array reduce polyfill

### ISSUE THREAD

**Issue by wilsonespina** [msn0/mdn-polyfills#59]
Is there any way we can have the Array.reduce polyfill from here:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce#Polyfill

**Comment by msn0** [comment]
Sure, I'll add it later this week.

**Comment by msn0** [comment]
@wilsonespina I've just added `Array.prototype.reduce`. 
You can find it in 📦 `mdn-polyfills@5.17.0`
