### ISSUE TITLE
'before' polyfill error in IE11

### ISSUE THREAD

**Issue by fvonellerts** [msn0/mdn-polyfills#64]
There is a small fault in the **Node.prototype.before** polyfill which results in a `ErrorNotFound` in IE11.

`this.insertBefore(o, this)` should be `this.parentNode.insertBefore(o, this)`

It has already been fixed on MDN: https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/before

**Comment by msn0** [comment]
@fvonellerts would you like to fix it and open a pull request?

**Comment by fvonellerts** [comment]
@msn0 so...?
