### ISSUE TITLE
Array.prototype.findIndex

### ISSUE THREAD

**Issue by elboletaire** [msn0/mdn-polyfills#9]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex?v=example#Polyfill

**Comment by msn0** [comment]
Version 3.3.0 with `Array.prototype.findIndex` is out. Please reinstall mdn-polyfills and
```js
import 'mdn-polyfills/Array.prototype.findIndex';
```

**Comment by elboletaire** [comment]
Thanks 😃
